version: '3'

services:

  backend:
    env_file: .env
    build:
      context: ./backend
    restart: on-failure
    volumes:
      - ./backend:/app
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - postgres_db

    networks:
      private_network:
        ipv4_address: 10.5.0.5

  postgres_db:
    env_file: .env
    image: postgres:11-alpine
    restart: on-failure
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    networks:
      private_network:
        ipv4_address: 10.5.0.6

  nginx:
    image: nginx:1.17.3-alpine
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - backend
    networks:
      private_network:
        ipv4_address: 10.5.0.7
      default:


networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16


volumes:
  postgres_db_volume:
