version: "3.4"

services:
  backend:
    container_name: checklists_backend_dev
    env_file: .env
    user: ${CURRENT_UID}
    build:
      context: ./backend
      args:
        - DEBUG=True
      target: deploy
    restart: on-failure
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./backend:/app
      - ./static:/app/static
      - ./media:/app/media
      - ./profiles:/app/profiles
    depends_on:
      - postgres_db
    networks:
      private_network:
        ipv4_address: 172.25.0.5

  postgres_db:
    container_name: checklists_postgres_db_dev
    env_file: .env
    image: postgres:11-alpine
    restart: on-failure
    command: -p ${POSTGRES_PORT}
    volumes:
      - checklists_db_data_dev:/var/lib/postgresql/data
    networks:
      private_network:
        ipv4_address: 172.25.0.6

  nginx:
    container_name: checklists_nginx_dev
    image: nginx:1.17-alpine
    restart: on-failure
    ports:
      - 8000:80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - backend
      - frontend
    networks:
      private_network:
        ipv4_address: 172.25.0.7
      default:

  frontend:
    container_name: checklists_frontend_dev
    env_file: .env
    user: ${CURRENT_UID}
    image: node:14.2.0-alpine3.11
    command: npm run serve
    volumes:
      - ./frontend:/app
    working_dir: /app
    restart: on-failure
    depends_on:
      - backend
    networks:
      private_network:
        ipv4_address: 172.25.0.8

  qcluster:
    image: checklists_backend
    container_name: checklists_qcluster_dev
    env_file: .env
    user: ${CURRENT_UID}
    volumes:
      - ./backend:/app/
      - ./static:/app/static
    restart: on-failure
    entrypoint: python3
    command: ./manage.py qcluster
    depends_on:
      - backend
      - postgres_db
    networks:
      private_network:
        ipv4_address: 172.25.0.9

  # pgadmin:
  #   container_name: checklists_pgadmin_dev
  #   env_file: .env
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgres_db
  #   ports:
  #     - 5555:8080
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  #   restart: on-failure
  #   volumes:
  #     - pgadmin_dev:/var/lib/pgadmin
  #   networks:
  #     private_network:
  #       ipv4_address: 172.25.0.10

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  checklists_db_data_dev:
  pgadmin_dev:
