version: '3'

services:
  backend:
    container_name: checklists_backend
    env_file: .env
    environment:
      - DEBUG=False
    build:
      context: ./backend
    restart: on-failure
    volumes:
      - ./backend:/app
    depends_on:
      - postgres_db
    networks:
      private_network:
        ipv4_address: 10.5.0.5

  postgres_db:
    container_name: checklists_postgres_db
    env_file: .env
    image: postgres:11-alpine
    restart: on-failure
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    networks:
      private_network:
        ipv4_address: 10.5.0.6

  nginx:
    container_name: checklists_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - backend
    networks:
      private_network:
        ipv4_address: 10.5.0.7
      default:

  postgres_backups:
    container_name: checklists_postgres_backups
    image: prodrigestivill/postgres-backup-local:11-alpine
    restart: on-failure
    depends_on:
      - postgres_db
    volumes:
      - /tmp/backups/:/backups/

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16


volumes:
  postgres_db_volume:
