version: '3'

services:

  backend:
    build: .
    restart: on-failure
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    networks:
      - nginx_network
      - db_network
    depends_on:
      - postgres_db
    env_file: .env

  nginx:
    image: nginx:1.17.3-alpine
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - backend
    networks:
      - nginx_network

  postgres_db:
    image: postgres:11-alpine
    restart: on-failure
    env_file: .env
    networks:
      - db_network
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  postgres_db_volume:
