version: '3'

services:

  backend:
    container_name: checklists_backend
    env_file: .env
    build:
      context: ./backend
    restart: on-failure
    volumes:
      - ./backend:/app
    depends_on:
      - postgres_db
    networks:
      private_network:
        ipv4_address: 10.5.0.5

  postgres_db:
    container_name: checklists_postgres_db
    env_file: .env
    image: postgres:11-alpine
    restart: on-failure
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    networks:
      private_network:
        ipv4_address: 10.5.0.6

  nginx:
    container_name: checklists_nginx
    image: nginx:1.17.3-alpine
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - backend
    networks:
      private_network:
        ipv4_address: 10.5.0.7
      default:

  frontend:
    container_name: checklists_frontend
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    working_dir: /app
    restart: on-failure
    networks:
      private_network:
        ipv4_address: 10.5.0.8

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16


volumes:
  postgres_db_volume:
