version: '3.4'

services:
  backend:
    container_name: checklists_backend
    env_file: .env
    build:
      context: ./backend
      args:
        - DEBUG=False
      target: deploy
    restart: always
    volumes:
      - ./backend:/app
      - checklists_media:/app/media
      - ./static:/app/static
    depends_on:
      - postgres_db
    networks:
      private_network:
        ipv4_address: 172.25.0.5

  postgres_db:
    container_name: checklists_postgres_db
    env_file: .env
    image: postgres:11-alpine
    restart: always
    command: -p ${POSTGRES_PORT}
    volumes:
      - checklists_db_data:/var/lib/postgresql/data
      - checklists_db_backups:/var/backups
    networks:
      private_network:
        ipv4_address: 172.25.0.6

  nginx:
    container_name: checklists_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static
      - checklists_media:/app/media
    depends_on:
      - backend
      - redis_cache
    networks:
      private_network:
        ipv4_address: 172.25.0.7
      default:

  #  postgres_backups:
  #    container_name: checklists_postgres_backups
  #    env_file: .env
  #    image: prodrigestivill/postgres-backup-local:11-alpine
  #    restart: always
  #    links:
  #      - postgres_db
  #    depends_on:
  #      - postgres_db
  #    volumes:
  #      - /tmp/backups/:/backups/
  #    networks:
  #      private_network:
  #        ipv4_address: 172.25.0.9


  redis_cache:
    container_name: checklists_redis_cache
    image: redis:5.0.6-alpine3.10
    depends_on:
      - backend
    volumes:
      - checklists_redis_data:/data
    networks:
      private_network:
        ipv4_address: 172.25.0.10


networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16


volumes:
  checklists_db_data:
    external:
      name: checklists_db_data
  checklists_db_backups:
    external:
      name: checklists_db_backups
  checklists_media:
    external:
      name: checklists_media
  checklists_redis_data:
    external:
      name: checklists_redis_data
