version: '3'

services:

  djangoapp:
    build: .
    restart: always
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    networks:
      - nginx_network
      - db_network
    depends_on:
      - database1

  nginx:
    image: nginx:1.17.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1:
    image: postgres:12-alpine
    restart: always
    env_file:
      - config/db/database1_env
    networks:
      - db_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  database1_volume:
