name: clrn stage CI

on:
  push:
    branches:
      - develop
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Create .env
      env:
        SECRET_KEY: CHANGEME!!!
        POSTGRES_DB: postgres_db
        POSTGRES_PASSWORD: mysecretpass
        POSTGRES_USER: postgresuser
        POSTGRES_HOST: 172.25.0.6
        POSTGRES_PORT: 5432
        VUE_APP_PROTOCOL: https
        VUE_APP_DOMAIN: checklists.stdfo.ru
        VUE_APP_NAME: checklists
        VUE_APP_DADATA_KEY: CHANGEME!!!
        PGADMIN_EMAIL: admin@example.com
        PGADMIN_PASSWORD: qweqweqwe
      run: touch .env
    - name: Create volumes
      run: |
        docker volume create checklists_db_data
        docker volume create checklists_db_backups
        docker volume create checklists_media
    - name: Make prod-upb
      run: make prod-upb
